### ISSUE TITLE
Tags and Categories pages won't work

### ISSUE THREAD

**Issue by anpig** [luswdev/hexo-theme-clean#2]
As title, nothing showed up when I clicked into the tags/categories page.
![image](https://user-images.githubusercontent.com/31090467/100496767-b0bb0e80-3191-11eb-9dae-a9ac5ee49da9.png)
Do I need to edit the md manually?

**Comment by Hugozys** [comment]
Run into similar issue. Looks like the information in the doc is incorrect. I managed to resolve this by changing `type: "tags"` to `layout: "tags"`. Basically add the following to the `index.md` in your tags directory:
```yaml
---
title: All tags
layout: "tags"
---
```
Then when I run the server locally, the tags page will render all the tags I defnied in other posts. Same for categories as well. 
Hope this helps.

**Comment by anpig** [comment]
@Hugozys It works! thanks
